### ISSUE TITLE
[v3] Width calculation for horizontal scrolling doesn't take padding into account

### ISSUE THREAD

**Issue by ibdknox** [codemirror/codemirror5#1049]
If you have a horizontal padding set per the comments in the css, like so:

``` css
.CodeMirror-lines {
  padding: 10px 0; /* Vertical padding around content */
}
.CodeMirror pre {
  padding: 0 35px 0 15px; /* Horizontal padding of content */
}
```

You are unable to scroll all the way to the right, presumably because the scrollbar calculation doesn't take that padding into account.
