### ISSUE TITLE
-moz-user-select Firefox Copy/Paste bug

### ISSUE THREAD

**Issue by azawawi** [codemirror/codemirror5#1250]
When the -moz-user-select CSS property is set to none for the body element, CodeMirror copy/paste functionality ceases to work under Firefox 18.0.2. I need to disable the text selection on everything but CodeMirror editors in my application. Other browsers do not suffer from the same bug.

``` css
body {
/* Disables CodeMirror copy/paste functionality */
-moz-user-select: none;      
}
```
