### ISSUE TITLE
YAML comments should only be highlighted when preceded by whitespace

### ISSUE THREAD

**Issue by stuartpb** [codemirror/codemirror5#1516]
Per [the YAML spec](http://yaml.org/spec/1.2/spec.html#comment//):

> Comments must be separated from other tokens by white space characters.

Therefore

``` yaml
# The following line ends with a comment
commented: Some text # followed by a comment
# The following line does NOT end with a comment
url: http://www.example.com/thisis#notacomment
```

CodeMirror highlights both instances of the hash and following content as comments.
