### ISSUE TITLE
SCSS Identation Issue

### ISSUE THREAD

**Issue by dubiousdavid** [codemirror/codemirror5#1533]
``` SCSS
padding: {
  top: 40px;
  bottom: 40px;
}
```

is rendered with double indentation for the children of "padding:".
