### ISSUE TITLE
CodeMirror-gutter height doesn't size properly on init & container expends instead of scrolls

### ISSUE THREAD

**Issue by JakobJingleheimer** [codemirror/codemirror5#1891]
In [codemirror.css:160](https://github.com/marijnh/CodeMirror/blob/master/lib/codemirror.css#L160)

``` css
.CodeMirror-gutter {
  white-space: normal;
  height: 100%;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  padding-bottom: 30px;
  margin-bottom: -32px;
  display: inline-block;
  /* Hack to make IE7 behave */
  *zoom:1;
  *display:inline;
}
```

`.CodeMirror-gutter` _would_ size properly with the above css, except for the following JavaScript, which overrides the height property at the element level. I can't figure out where JavaScript is getting the incorrect height—everything else inside of the `.CodeMirror` container is sized properly.

https://github.com/marijnh/CodeMirror/blob/master/lib/codemirror.js#L324

``` javascript
d.gutters.style.height = Math.max(totalHeight, d.scroller.clientHeight - scrollerCutOff) + "px";
```

It does correct itself as soon as the content is changed, when it becomes .CodeMirror-gutter<strong>s<strong>.
