### ISSUE TITLE
Reflect original textarea validation state

### ISSUE THREAD

**Issue by heruan** [codemirror/codemirror5#2016]
A required `textarea` such as

``` html
<textarea id="cm" required></textarea>
```

can be highlighted if empty (i.e. invalid) with

``` css
textarea:invalid {
  border-color: red;
}
```

It would be nice if CodeMirror could reflect the validation state, e.g. with a `invalid` class when the original `textarea` has the `invalid` property true.
