### ISSUE TITLE
[test] failure firefox linux

### ISSUE THREAD

**Issue by peterkroon** [codemirror/codemirror5#2053]
5 failures

less_variable
    TypeError: mode.startState is not a function (mode_test.js:105)

less_amp
    TypeError: mode.startState is not a function (mode_test.js:105)

less_mixin
    TypeError: mode.startState is not a function (mode_test.js:105)

less_nest
    TypeError: mode.startState is not a function (mode_test.js:105)

gfm_notALink

`````` css
foo {color:black;}
```http://www.example.com/

expected:
```css  foo ·{ color   :   black   ;}  ``` http://www.example.com/
comment tag null    property    null    keyword null    comment link
observed:
```css  foo ·{ color   :   black   ;}  ``` http://www.example.com/
comment tag null    property    operator    keyword null    comment link
``````
