### ISSUE TITLE
Use case that break SCSS parsing

### ISSUE THREAD

**Issue by MoOx** [codemirror/codemirror5#2087]
This is valid Scss

``` scss
  li {
    font: {
      family: serif;
      weight: bold;
      size: 1.2em;
    }
  }
```

(which render correctly here)

But CodeMirror doesn't render it correctly:

![screen shot 2013-12-29 at 19 33 54](https://f.cloud.github.com/assets/157534/1819876/cb53ac9a-70b7-11e3-86a2-dc8350882d38.png)

It recognize the family & weight as tag, but they are not. They are property, like size.
I'm assuming from [this line](https://github.com/marijnh/CodeMirror/blob/master/mode/css/css.js#L386) which contains "size" as keyword, that adding family & wieght as keyword too will fix it.
But it seems a little bit more complicated because they are keyword just when you are under a font block.
Note: I agree this is a rare use case.

As you can see above, pygment (used by GitHub) doesn't handle `wrong` property name.

``` scss
li {
  family: serif;
  weight: bold;
  size: 1.2em;
}
```

So not sure how to fix that, I'm need to codemirror & only use it for highlight through [highlight-codemirror](https://github.com/ForbesLindesay/highlight-codemirror).
