### ISSUE TITLE
[css-scss-less] indentation failure

### ISSUE THREAD

**Issue by peterkroon** [codemirror/codemirror5#2131]
- Go to: http://codemirror.net/mode/css/index.html
- `Ctrl-A` and paste code below in editor
- `Ctrl-A` => `Tab` => `Shift-Tab`

Note that `src` is colorized red. Adding the the property to the list will fix this I think.

``` css

@font-face {
  font-family: 'customfont';
  src: url('webfont.eot');
  src: url('webfont.eot?#iefix') format('embedded-opentype'),
       url('webfont.woff') format('woff'),
       url('webfont.ttf') format('truetype'),
       url('webfont.svg#customfont') format('svg');
  font-weight: normal;
  font-style: normal;
}

```

the result in the css mode looks like:

``` css

@font-face {
  font-family: 'customfont';
  src: url('webfont.eot');
  src: url('webfont.eot?#iefix') format('embedded-opentype'),
    url('webfont.woff') format('woff'),
    url('webfont.ttf') format('truetype'),
    url('webfont.svg#customfont') format('svg');
  font-weight: normal;
  font-style: normal;
}

```

(you see that the `url` are not aligned anymore)

in scss:

``` css

@font-face {
  font-family: 'customfont';
  src: url('webfont.eot');
  src: url('webfont.eot?#iefix') format('embedded-opentype'),
  url('webfont.woff') format('woff'),
  url('webfont.ttf') format('truetype'),
  url('webfont.svg#customfont') format('svg');
  font-weight: normal;
  font-style: normal;
}

```

and in the less mode the indendation is the same as in the scss mode but the highlighting is completely different
