### ISSUE TITLE
Cannot Copy/Paste from/to CodeMirror using a mouse right-click menu with CSS3 rules applied

### ISSUE THREAD

**Issue by wiinci** [codemirror/codemirror5#2154]
Browsers: Firefox 26.0
OS: OSX 10.9.1
CodeMirror: Version 3.21
#### Problem:

Copying, pasting from CodeMirror is not available when the some CSS3 rules are applied to the parent container.
#### Simplified test case:

http://jsbin.com/ihunin/328/

Copy/paste options are not available in the mouse right-click menu with `margin` **and** `backface-visibility` + `transform` applied:

``` css
body {
  backface-visibility: hidden;
  transform: translate3d(0,0,0);
  /* Turning off margin fixes this issue */
  /* margin: 0; */
}
```

Turning off the `margin` on the body fixes this issue. However, its not possible in our case to turn off margins or remove the CSS3 rules to prevent content flicker on mobile devices.
