### ISSUE TITLE
[css][scss][less] indentation failure when missing ;

### ISSUE THREAD

**Issue by peterkroon** [codemirror/codemirror5#2162]
- Go to http://codemirror.net/mode/css/index.html and paste code below in editor

``` css
div{
  width:560px;
  text-align:justify
}
```
- `Tab` => `Shift-Tab`

The result looks like:

``` css
div{
  width:560px;
  text-align:justify
    }
```

This is because there is no `;` present at the end of the second property value.
