### ISSUE TITLE
[less] Function in linear-gradient is marked with different tokens

### ISSUE THREAD

**Issue by 0b10011** [codemirror/codemirror5#2551]
Assuming the following code:

``` less
.foo {
  background-image:fade(#000, 20%);
  border-image:linear-gradient(
    to bottom,
    fade(#000, 20%) 0%,
    fade(#000, 20%) 100%
  );
}
```
- `fade` is `cm-variable` in `background-image`
- `fade` is `cm-property` for `0%` in `border-image`
- `fade` is `cm-variable` for `100%` in `border-image`
## Expected results

`fade` should be the same throughout.
