### ISSUE TITLE
Error: Required option 'getAnnotations' missing (lint addon) 

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [codemirror/codemirror5#2674]
Hello, I'm using a compressed CodeMirror script and attempting to enable Javascript linting functionality and getting the above error (all other add-ons work, just not this one).

Is it possible that linting won't work if a compressed all-in-one CodeMirror script is used?

The reason I ask is because I think I'm doing everything correctly with the only significant difference from the demo page being the order of scripts loading because the lint demo example page shows the jshint script referenced _after_ codemirror.js and /mode/javascript/javascript.js but _before_ /addon/lint/lint.js and /addon/lint/javascript-lint.js etc, however I'm using the single compressed script:

```
/* CodeMirror - Minified & Bundled
   Generated on 1/7/2014 with http://codemirror.net/doc/compress.html
   Version: HEAD

   CodeMirror Library:
   - codemirror.js
   Modes:
   - css.js
   - htmlmixed.js
   - javascript.js
   - xml.js
   Add-ons:
   - brace-fold.js
   - closebrackets.js
   - closetag.js
   - colorize.js
   - comment.js
   - comment-fold.js
   - css-hint.js
   - dialog.js
   - foldcode.js
   - foldgutter.js
   - html-hint.js
   - javascript-hint.js
   - javascript-lint.js
   - json-lint.js
   - lint.js
   - mark-selection.js
   - match-highlighter.js
   - matchbrackets.js
   - matchtags.js
   - search.js
   - searchcursor.js
   - show-hint.js
   - trailingspace.js
   - xml-fold.js
   - xml-hint.js
   Keymaps:
   - sublime.js
 */
...etc..
```

I've tried loading JSHINT before the CodeMirror script, and after but still get the same error.

This is my config:

```
 matchBrackets: true,
                autoCloseBrackets: true,
                matchTags: true,
                showTrailingSpace: true,
                lineNumbers: true,
                highlightSelectionMatches: true,
                extraKeys: {
                    'Ctrl-Q': function(cm) {
                        cm.foldCode(cm.getCursor());
                    },
                    'Ctrl-Space': 'autocomplete'
                },
                lint: true,
                foldGutter: true,
                gutters: ['CodeMirror-lint-markers','CodeMirror-linenumbers', 'CodeMirror-foldgutter'],
                mode: 'javascript'
```
