### ISSUE TITLE
addWiget overlap

### ISSUE THREAD

**Issue by MasseGuillaume** [codemirror/codemirror5#2713]
I'm using cm.addWidget({line: 3, ch: Infinity}, elem, false, "over") but it overlap with the next line.

see https://github.com/MasseGuillaume/ScalaKata/issues/15

is there a way to avoid this ?

**Comment by MasseGuillaume** [comment]
@marijnh it can also be done with lineWidget. This was inspired by chromium devtools

http://codepen.io/anon/pen/XbGZZN?editors=011

```html
<textarea></textarea>
```
```css
.CodeMirror-linewidget {
  overflow: visible !important;
  position: relative;
}
.CodeMirror-linewidget .inline {
  position: absolute;
  bottom: 0;
  overflow: hidden;
  margin-left: 10px;
  text-decoration: underline;
}
```

```js
var editor = CodeMirror.fromTextArea(document.querySelector("textarea"));

editor.getDoc().setValue([
  "1+1",
  "2+2",
  "3+3"
].join("\n"));

["2", "4", "6"].forEach(function(v, i) {
  var node = document.createElement("pre"),
    basePos = new CodeMirror.Pos(i, 0),
    offsetPos = new CodeMirror.Pos(
      i, editor.getDoc().getLine(i).length
    ),
    base = editor.cursorCoords(basePos),
    offset = editor.cursorCoords(offsetPos),
    node = document.createElement("pre");

  node.style.left = (offset.left - base.left) + "px";
  node.className = "inline";
  node.textContent = v;
  editor.addLineWidget(i, node);
});
```
