### ISSUE TITLE
CSS Animated cursor blinking

### ISSUE THREAD

**Issue by colelawrence** [codemirror/codemirror5#2733]
I guess this was mentioned in #1044, but it would be nice to have fadey css animated cursors as an option.
I have an example of a patched codemirror running with fadey cursors, but my implemented code does not have an on or off option it's just a modification of the [`restartBlinking` function](https://github.com/marijnh/CodeMirror/blob/2f14f52e24b35323081878d598465f390db1e955/lib/codemirror.js#L1390)

Example: [http://zombiehippie.github.io/perfect-codemirror/](http://zombiehippie.github.io/perfect-codemirror/)

Note that the configuration I've put on CodeMirror are entirely personal preference.

This is how the code changes in said function:

``` javascript
    // This is a patch I've written over my codemirror install to enable fancy blinking

    // Cursor-blinking
    function restartBlink(cm) {
      if (!cm.state.focused) return;
      var display = cm.display;
      clearInterval(display.blinker);
      // My code ZombieHippie@github.com
      display.cursorDiv.className = display.cursorDiv.className.replace(" blinking","");
      display.blinker = setTimeout(function () {
        display.cursorDiv.className += " blinking";
      }, cm.options.cursorBlinkRate);
      // The following commented code is the original code
      /*
      var on = true;
      display.cursorDiv.style.visibility = "";
      if (cm.options.cursorBlinkRate > 0)
        display.blinker = setInterval(function() {
          display.cursorDiv.style.visibility = (on = !on) ? "" : "hidden";
        }, cm.options.cursorBlinkRate);
      else if (cm.options.cursorBlinkRate < 0)
        display.cursorDiv.style.visibility = "hidden";
      */
    }
```

And the css:

``` css
    .CodeMirror-focused div.CodeMirror-cursors.blinking {
      -webkit-animation: CodeMirror-cursors 1.06s infinite;
      animation: CodeMirror-cursors 1.06s infinite;
    }
    @-webkit-keyframes CodeMirror-cursors
    {
      from,to,85%,15%  {opacity: 1}
      65%, 35% {opacity: 0}
    }
    @keyframes CodeMirror-cursors
    {
      from,to,85%,15%  {opacity: 1}
      65%, 35% {opacity: 0}
    }
```

If this is a desired feature now or later, it is now documented here, and someone can implement it themselves if it doesn't get pulled into the master repo.
