### ISSUE TITLE
min-height on setSize

### ISSUE THREAD

**Issue by gmaggess** [codemirror/codemirror5#2835]
Hi Gurus,

I'm trying to set a min-height for codemirror. The reason behind is that I need codemirror to have a minimum height in case it does not have any content. I'm currently using the setHeight method, but it stops codemirror from expanding if the content size overflows the specified height.

Is there a workaround for this problem? Any help is appreciated.

Cheers,
George

**Comment by sn3p** [comment]
> You have to use CSS for this. Give the `.CodeMirror-scroll` class a `min-height` style.

This works, but without a small detail: the mouse only shows `cursor: text;` for the actual lines.

To solve this you can fix it like:

```css
.CodeMirror-scroll {
  cursor: text;
  min-height: 200px;
}
```

Or apply the min-height to `.CodeMirror-lines` instead:

```css
.CodeMirror-lines {
  min-height: 200px;
}
```
