### ISSUE TITLE
How to increase line height?

### ISSUE THREAD

**Issue by eldargab** [codemirror/codemirror5#2941]
Hi,

I tried to increase the line height via

``` css
CodeMirror pre {
  line-height: 1.5;
}
```

but cursor and selection heights left unadjusted. 

Is there some way to get more space between lines?
