### ISSUE TITLE
Scrolling on Android 4.* (Stock browser)

### ISSUE THREAD

**Issue by ikrestov** [codemirror/codemirror5#694]
This issue as far as I tested appears only on tablets with stock browser (chrome).

It seems due to the bug in a browser scrolling does not work, because **scroll** event is not fired on `div.CodeMirror-scroll`, when `overflow-y:hidden` is set.

While testing, changing it to `overflow-y: scroll/ auto` allowed scrolling, only down, though. (Naturally it created second scroll bar and messed up other styles)
So I believe problem lies there.

Tested with:
- Android Jelly Bean - not working **Tablet**
- Android ICS - working **Phone**

To replicate open any current demo and add more lines/ data and then try to scroll.

So far I couldn't come up with a proper fix.

My temporary workaround, to at least allows some kind of scrolling is making _solid_ scrollbar.

``` css
.CodeMirror-scrollbar::-webkit-scrollbar {
    width: 50px;
    height: 16px;
}

.CodeMirror-scrollbar::-webkit-scrollbar-thumb {
    min-height: 30px;
    padding-top: 100px;
    background-clip: padding-box;
    background-color: rgba(0, 0, 0, .2);
    -webkit-box-shadow: inset 1px 1px 0 rgba(0, 0, 0, .10),inset 0 -1px 0 rgba(0, 0, 0, .07);
}

.CodeMirror-scrollbar::-webkit-scrollbar-button {
    height: 0;
    width: 0;
}
```
