### ISSUE TITLE
Duotone Theme Color contrast is not up to WCAG standards for comments

### ISSUE THREAD

**Issue by robert-j-webb** [codemirror/codemirror5#7087]
First of all, thanks for the work, great project 👏 

While using the Duotone themes, I noticed that the comment style was under the WCAG contrast ratio for Dark Mode and Light mode

Chrome Dev Tools contrast ratio tool: 

![Screenshot 2024-02-28 at 1 13 39 PM](https://github.com/codemirror/codemirror5/assets/1647322/de955f4d-3a5d-49bf-9ae6-da3566f9cdc7)

Visible Code: 

![image](https://github.com/codemirror/codemirror5/assets/1647322/e123c746-66ec-4146-8210-94c9aff5569d)

Chrome Dev Tools contrast ratio tool: 

![Screenshot 2024-02-28 at 1 11 51 PM](https://github.com/codemirror/codemirror5/assets/1647322/17eca6ef-1738-4e9d-972e-6c1b0c0d9a1b)

Visible Code: 
![image](https://github.com/codemirror/codemirror5/assets/1647322/b6c2988c-616d-4472-ade8-74c787db2677)

As you can see, they're quite under what's recommended for accessibility - especially with light mode, you can see just how difficult it is to read here. 

I'm not sure if there's a different setup for updating themes, but I found these CSS rules / Colors to be WCAG compliant and somewhat on theme.

Also this functions as a workaround for other users with this issue:

```css
.cm-s-duotone-light span.cm-bracket,
.cm-s-duotone-light span.cm-comment {
  color: #6f6e6a !important;
}

.cm-s-duotone-dark span.cm-bracket,
.cm-s-duotone-dark span.cm-comment {
  color: #a7a5b2 !important;
}
```

Looks like: 

Light: 

![image](https://github.com/codemirror/codemirror5/assets/1647322/78bc5027-b154-4bba-897b-ecd334e93d93)

Dark:

![image](https://github.com/codemirror/codemirror5/assets/1647322/efa70afd-8c80-4cac-9208-13bfccf81d51)
