### ISSUE TITLE
Gutter mark styling is not applied in Chrome

### ISSUE THREAD

**Issue by Leonya** [codemirror/codemirror5#836]
Code:

``` javascript
var collapsedMark = document.createElement('span');
collapsedMark.className = 'CodeMirror-mark-collapsed';
collapsedMark.innerHTML = '▶';
ed.setGutterMarker(ed.getLineHandle(line), 'CodeMirror-folded', collapsedMark);
```

``` css
.CodeMirror-mark-collapsed {
    margin-left: 4px;
    color: #999;
}
```

Works fine in Firefox, but not in Chrome (21).
