### ISSUE TITLE
Add support for manual resizing

### ISSUE THREAD

**Issue by flack** [codemirror/codemirror5#850]
Sorry if this is a duplicate, but a quick search of the issue list found nothing that seemed related.

I was wondering if CodeMirror could be made to support the CSS resize attribute. So that I could write something like this:

``` css
.CodeMirror-scroll
{
    resize: vertical;
}
```

In the current release (2.34), this actually renders a resize handle, but I can't move it. Or am I just doing it wrong?
